<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

    <xacro:property name="camera_length" value="0.01" />
    <xacro:property name="camera_width" value="0.1" />
    <xacro:property name="camera_height" value="0.05" />

    <!-- create shape of camera as a link -->
    <link name="camera_link">
        <visual>
            <geometry>
                <!-- size doesn't matter for camera so it can small -->
                <box size="${camera_length} ${camera_width} ${camera_height}" />
            </geometry>
            <!-- if don't put <origin> it will equal 0 by default -->
            <material name="grey" />
        </visual>
        <collision>
            <geometry>
                <box size="${camera_length} ${camera_width} ${camera_height}" />
            </geometry>
        </collision>
        <xacro:box_inertia m="0.1" l="${camera_length}" w="${camera_width}"  h="${camera_height}"  
                           xyz="0 0 0"  rpy="0 0 0" />
    </link>

    <!-- create joint for camera -->
    <joint name="base_camera_joint" type="fixed">
        <parent link="base_link" /> 
        <child link="camera_link" />
        <!-- camera shuld not sink in another link.it will have problem whe visualize image -->
        <origin xyz="${(base_length / 2.0) + (camera_length / 2.0)} 0 ${base_height / 2.0}" rpy="0 0 0" /> 
    </joint>

    <!-- for ros(Gazebo) and opencv can operate on the camera frame correctly -->
    <!-- //////////////////////////////////////////////////////////////////////// -->
    <link name="camera_link_optical"></link>

    <joint name="camera_optical_joint" type="fixed">
        <!-- these values have to be these values otherwise the gazebo camera
            image won't be aligned properly with the frame it is supposedly
            originating from -->
        <origin xyz="0 0 0" rpy="${-pi/2} 0 ${-pi/2}"/>
        <parent link="camera_link"/>
        <child link="camera_link_optical"/>
    </joint>
    <!-- //////////////////////////////////////////////////////////////////////// -->


    <!-- add camera in gazebo -->
    <gazebo reference="camera_link">

        <!-- add color on camera in gazebo (it will not same in arviz) -->
        <material>Gazebo/Red</material>

        <!-- add sensor tag for camera -->
        <sensor name="camera_sensor" type="camera">

            <!-- it common for every sensor to put 3 thing -->
            <!-- ////////////////////////////////////////////////////////////////////// -->
            <!-- pose = position + orientation -->
            <!-- it is origin that where you want the sensor connect to camera_link -->
            <pose>0 0 0 0 0 0</pose>
            
            <!-- for able(switch on/off) to visualize camera on gazebo -->
            <!-- and it help to see that camera and what camera see -->
            <visualize>true</visualize>

            <!-- it is rate(Hz) gazebo is going to read data from the sensor -->
            <updata_rate>10.0</updata_rate>
            <!-- ////////////////////////////////////////////////////////////////////// -->

            <!-- add gazebo_ros_camera.hpp plugin from ros-simulation/gazebo_ros_pkgs -->
            <!-- name can change but filename can't change -->
            <plugin name="camera_controller" filename="libgazebo_ros_camera.so">
                <!-- frame_name is name of link that the camera is attached -->
                <!-- <frame_name>camera_link</frame_name> -->
                
                <!-- for use OpenCV with Gazebo -->
                <frame_name>camera_link_optical</frame_name>
            </plugin>

        </sensor>
    </gazebo>
</robot>