<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">
    <!-- create variable by xacro -->
    <xacro:property name="base_length" value="0.6" />
    <xacro:property name="base_width" value="0.4" />
    <xacro:property name="base_height" value="0.2" />
    <xacro:property name="wheel_radius" value="0.1" />
    <xacro:property name="wheel_length" value="0.05" />

    <link name="base_footprint" />
    
    <!-- create base link(rigit part) -->
    <link name="base_link">
        <visual>
            <geometry>
                <box size="${base_length} ${base_width} ${base_height}" /> <!-- use variable -->
            </geometry>
            <origin xyz="0 0 ${base_height / 2.0}" rpy="0 0 0" /> 
            <material name="blue" />
        </visual>

        <!-- create collision tag -->
        <!-- for can collision another object -->
        <collision>
            <!-- use same shape as this link -->
            <geometry>
                <box size="${base_length} ${base_width} ${base_height}" /> <!-- use variable -->
            </geometry>
            <origin xyz="0 0 ${base_height / 2.0}" rpy="0 0 0" /> 
        </collision>

        <!-- use function inetia from common properties file -->
        <!-- for appear in gazebo -->
        <xacro:box_inertia m="5.0" l="${3*base_length}" w="${2*base_width}" h="${2*base_height}" 
                           xyz="0 0 ${base_height / 2.0}" rpy="0 0 0" />

    </link>

    <!-- create function for wheel link -->
    <xacro:macro name="wheel_link" params="prefix"> 
        <link name="${prefix}_wheel_link">
            <visual>
                <geometry>
                    <cylinder radius="${wheel_radius}" length="${wheel_length}" />
                </geometry>
                <origin xyz="0 0 0" rpy="${pi / 2.0} 0 0" /> <!-- use pi by xacro -->
                <material name="grey" />
            </visual>

            <collision>
                <geometry>
                    <cylinder radius="${wheel_radius}" length="${wheel_length}" />
                </geometry>
                <origin xyz="0 0 0" rpy="${pi / 2.0} 0 0" /> <!-- use pi by xacro -->
            </collision>

            <xacro:cylinder_inertia m="1.0" r="${2*wheel_radius}" l="${2*wheel_length}" 
                                    xyz="0 0 0" rpy="${pi / 2.0} 0 0" />

        </link>
    </xacro:macro>

    <!-- use function wheel link -->
    <xacro:wheel_link prefix="right"/>
    <xacro:wheel_link prefix="left"/>

    <!-- create caster wheel link(rigit part) -->
    <link name="caster_wheel_link">
        <visual>
            <geometry>
                <sphere radius="${wheel_radius / 2.0}" />
            </geometry>
            <origin xyz="0 0 0" rpy="0 0 0" /> 
            <material name="grey" />
        </visual>

        <collision>
            <geometry>
                <sphere radius="${wheel_radius / 2.0}" />
            </geometry>
            <origin xyz="0 0 0" rpy="0 0 0" /> 
        </collision>

        <xacro:sphere_inertia m="0.5" r="${2*wheel_radius / 2.0}" 
                              xyz="0 0 0" rpy="0 0 0" />

    </link>

<!-- ////////////////////////////////////////////////////////////////// -->

    <!-- create base joint -->
    <joint name="base_joint" type="fixed">
        <parent link="base_footprint" /> 
        <child link="base_link" />
        <origin xyz="0 0 ${wheel_radius}" rpy="0 0 0" />
    </joint>

    <!-- create base right wheel joint -->
    <joint name="base_right_wheel_joint" type="continuous">
        <parent link="base_link" /> 
        <child link="right_wheel_link" />
        <origin xyz="${-base_length / 4.0} ${-(base_width + wheel_length) / 2.0} 0" rpy="0 0 0" /> <!-- -base_length / 4.0 = -0.15 -->
        <axis xyz="0 1 0" />
    </joint>

    <!-- create base left wheel joint -->
    <joint name="base_left_wheel_joint" type="continuous">
        <parent link="base_link" /> 
        <child link="left_wheel_link" />
        <origin xyz="${-base_length / 4.0} ${(base_width + wheel_length) / 2.0} 0" rpy="0 0 0" /> 
        <axis xyz="0 1 0" />
    </joint>

    <!-- create base caster wheel joint -->
    <joint name="base_caster_wheel_joint" type="fixed">
        <parent link="base_link" /> 
        <child link="caster_wheel_link" />
        <origin xyz="${base_length / 3.0} 0 ${-wheel_radius / 2.0}" rpy="0 0 0" /> <!-- -base_length / 2.0 = 0.2 -->
    </joint>

</robot>