<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

    <xacro:property name="arm_base_length" value="0.1" />
    <xacro:property name="arm_base_width" value="0.1" />
    <xacro:property name="arm_base_height" value="0.02" />
    <xacro:property name="arm_radius" value="0.02" />
    <xacro:property name="arm_length" value="0.3" />
    
    <link name="arm_base_link">
        <visual>
            <geometry>
                <box size="${arm_base_length} ${arm_base_width} ${arm_base_height}" /> <!-- use variable -->
            </geometry>
            <origin xyz="0 0 0" rpy="0 0 0" /> 
            <material name="orange" />
        </visual>
        <collision>
            <geometry>
                <box size="${arm_base_length} ${arm_base_width} ${arm_base_height}" /> <!-- use variable -->
            </geometry>
            <origin xyz="0 0 0" rpy="0 0 0" />  
        </collision>
        <xacro:box_inertia m="0.5" l="${arm_base_length}" w="${arm_base_width}" h="${arm_base_height}" 
                           xyz="0 0 0" rpy="0 0 0" />
    </link>

    <xacro:macro name="arm_link" params="prefix color">
        <link name="${prefix}_link">
            <visual>
                <geometry>
                    <cylinder radius="${arm_radius}" length="${arm_length}" />
                </geometry>
                <origin xyz="0 0 0.15" rpy="0 0 0" /> 
                <material name="${color}" />
            </visual>
            <collision>
                <geometry>
                    <cylinder radius="${arm_radius}" length="${arm_length}" />
                </geometry>
                <origin xyz="0 0 0.15" rpy="0 0 0" />
            </collision>
            <xacro:cylinder_inertia m="0.3" r="${arm_radius}" l="${arm_length}" 
                                        xyz="0 0 0.15" rpy="0 0 0" />
        </link>
    </xacro:macro>

    <xacro:arm_link prefix="forearm" color="yellow"/>
    <xacro:arm_link prefix="hand" color="orange"/>

<!-- //////////////////////////////////////////////////////////////////////////////// -->

    <joint name="base_arm_base_joint" type="fixed">
        <parent link="base_link" /> 
        <child link="arm_base_link" />
        <origin xyz="${(base_length - arm_base_length) / 2} 0 ${base_height + (arm_base_height / 2)}" rpy="0 0 0" /> <!-- -base_length / 2.0 = 0.2 -->
    </joint>

    <joint name="arm_base_forearm_joint" type="revolute">
        <parent link="arm_base_link" /> 
        <child link="forearm_link" />
        <origin xyz="0 0 0.01" rpy="0 0 0" />
        <axis xyz="0 1 0" />
        <limit effort="100" lower="0" upper="${pi / 2.0}" velocity="100" />
        <dynamic damping="0.1" friction="0.05" />
    </joint>

    <joint name="forearm_hand_joint" type="revolute">
        <parent link="forearm_link" /> 
        <child link="hand_link" />
        <origin xyz="0 0 0.3" rpy="0 0 0" />
        <axis xyz="0 1 0" />
        <limit effort="100" lower="0" upper="${pi / 2.0}" velocity="100" />
        <dynamic damping="0.1" friction="0.05" />
    </joint>

    
</robot>